-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NotificationType" ADD VALUE 'UPLOAD_PROOF';
ALTER TYPE "NotificationType" ADD VALUE 'SERVICE_REQUEST_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'SERVICE_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'SERVICE_REQUEST_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_SUCCESSFUL';
ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE 'INQUIRY_RESPONSE';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'POST_LIKED';
ALTER TYPE "NotificationType" ADD VALUE 'POST_COMMENTED';
ALTER TYPE "NotificationType" ADD VALUE 'POST_SHARED';
ALTER TYPE "NotificationType" ADD VALUE 'POST_REPLIED';

-- AlterTable
ALTER TABLE "notification-toggle" ADD COLUMN     "INQUIRY_RESPONSE" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "NEW_ORDER" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ORDER_UPDATE" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "PAYMENT_FAILED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "PAYMENT_SUCCESSFUL" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "POST_COMMENTED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "POST_LIKED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "POST_REPLIED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "POST_SHARED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "REVIEW_RECEIVED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "SERVICE_REQUEST_ACCEPTED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "SERVICE_REQUEST_CANCELLED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "SERVICE_REQUEST_REJECTED" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "UPLOAD_PROOF" BOOLEAN NOT NULL DEFAULT true;
