export enum ENVEnum {
    NODE_ENV = "NODE_ENV",
    DATABASE_URL = "DATABASE_URL",
    OAUTH_CLIENT_ID = "OAUTH_CLIENT_ID",
    PORT = "PORT",
    BASE_URL = "BASE_URL",

    JWT_SECRET = "JWT_SECRET",
    JWT_EXPIRES_IN = "JWT_EXPIRES_IN",

    MAIL_USER = "MAIL_USER",
    MAIL_PASS = "MAIL_PASS",

    SUPER_ADMIN_EMAIL = "SUPER_ADMIN_EMAIL",
    SUPER_ADMIN_PASS = "SUPER_ADMIN_PASS",

    ADMIN_EMAIL = "ADMIN_EMAIL",
    ADMIN_PASS = "ADMIN_PASS",
    ADMIN_PHONE = "ADMIN_PHONE",

    REDIS_URL = "REDIS_URL",
    REDIS_HOST = "REDIS_HOST",
    REDIS_PORT = "REDIS_PORT",

    CLOUDINARY_CLOUD_NAME = "CLOUDINARY_CLOUD_NAME",
    CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY",
    CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET",

    TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID",
    TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN",
    TWILIO_PHONE_NUMBER = "TWILIO_PHONE_NUMBER",

    GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
    GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
    GOOGLE_CALLBACK_URL = "GOOGLE_CALLBACK_URL",

    ACCESS_KEY = "ACCESS_KEY",
    ACCESS_SECRET = "SECRET_KEY",
    BUCKET_NAME = "XXXXXXXXXXX",
    BUCKET_REGION = "BUCKET_REGION",
}
