services:
    app:
        image: softvence/jconnect-backend:latest
        container_name: jconnect-backend
        profiles:
            - prod
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    db:
        image: postgres:16-alpine
        container_name: pg-db
        profiles:
            - dev
            - prod
        environment:
            - POSTGRES_USER=jconnect
            - POSTGRES_PASSWORD=jconnect
            - POSTGRES_DB=jconnect_db
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
<<<<<<< HEAD
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
=======
            test: ["CMD-SHELL", "pg_isready -U jconnect -d jconnect_db"]
>>>>>>> 99eb196e7a03f2b44c9c73a217e9956bd0c46d70
            interval: 10s
            timeout: 5s
            retries: 5

        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        profiles:
            - dev
            - prod
        command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
        volumes:
            - redis_data:/var/lib/redis/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 3s
            retries: 5
            start_period: 5s
        restart: unless-stopped

    caddy:
        image: caddy:latest
        profiles:
            - prod
        container_name: caddy_server
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp" # HTTP/3 support
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - app
        restart: always

volumes:
    caddy_data:
    caddy_config:
    postgres_data:
        driver: local
    redis_data:
        driver: local

networks:
    default:
