-- AlterTable
ALTER TABLE "services" ADD COLUMN     "isPost" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "withdrawals" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
